// Code generated by op-codegen - DO NOT EDIT MANUALLY

import { InnerClient } from "./core.js";
import { SecretsApi, Secrets } from "./secrets.js";
import { ItemsApi, Items } from "./items.js";
import { VaultsApi, Vaults } from "./vaults.js";
import { EnvironmentsApi, Environments } from "./environments.js";
import { GroupsApi, Groups } from "./groups.js";
import { CredentialBrokerApi, CredentialBroker } from "./credential_broker.js";

export class Client {
  public secrets: SecretsApi;
  public items: ItemsApi;
  public vaults: VaultsApi;
  public environments: EnvironmentsApi;
  public groups: GroupsApi;

  public constructor(innerClient: InnerClient) {
    this.secrets = new Secrets(innerClient);
    this.items = new Items(innerClient);
    this.vaults = new Vaults(innerClient);
    this.environments = new Environments(innerClient);
    this.groups = new Groups(innerClient);
  }
}

export class WorkloadClient {
  public credentialBroker: CredentialBrokerApi;

  public constructor(innerClient: InnerClient) {
    this.credentialBroker = new CredentialBroker(innerClient);
  }
}

export class OAuthClient {
  public credentialBroker: CredentialBrokerApi;

  public constructor(innerClient: InnerClient) {
    this.credentialBroker = new CredentialBroker(innerClient);
  }
}
