// Code generated by op-codegen - DO NOT EDIT MANUALLY

import { InvokeConfig, InnerClient, SharedCore } from "./core.js";
import {
  CredentialReference,
  EnvironmentCredential,
  ReviverFunc,
} from "./types.js";

/**
 * Read environment credentials — a bundle of environment variables — from
 * the 1Password Credential Broker.
 *
 * Accessed as `client.credential_broker.environment` in the generated SDK
 * bindings.
 */
export interface CredentialBrokerEnvironmentApi {
  /**
   * Fetch the environment credential identified by `credential_reference`.
   *
   * In addition to transport, keyset-decryption, and enclave errors surfaced as [Error::Internal],
   * fails with [Error::InvalidCredentialReference] if the reference is malformed
   * or does not name an environment credential, or with [Error::CredentialReferenceAccountMismatch]
   * if it belongs to a different account than the authenticated client.
   */
  get(credentialReference: CredentialReference): Promise<EnvironmentCredential>;
}

export class CredentialBrokerEnvironment
  implements CredentialBrokerEnvironmentApi
{
  #inner: InnerClient;

  public constructor(inner: InnerClient) {
    this.#inner = inner;
  }

  /**
   * Fetch the environment credential identified by `credential_reference`.
   *
   * In addition to transport, keyset-decryption, and enclave errors surfaced as [Error::Internal],
   * fails with [Error::InvalidCredentialReference] if the reference is malformed
   * or does not name an environment credential, or with [Error::CredentialReferenceAccountMismatch]
   * if it belongs to a different account than the authenticated client.
   */
  public async get(
    credentialReference: CredentialReference,
  ): Promise<EnvironmentCredential> {
    const invocationConfig: InvokeConfig = {
      invocation: {
        clientId: this.#inner.id,
        parameters: {
          name: "CredentialBrokerEnvironmentVariablesRead",
          parameters: {
            credential_reference: credentialReference,
          },
        },
      },
    };
    return JSON.parse(
      await this.#inner.invoke(invocationConfig),
      ReviverFunc,
    ) as EnvironmentCredential;
  }
}
