// Code generated by op-codegen - DO NOT EDIT MANUALLY

import { InvokeConfig, InnerClient, SharedCore } from "./core.js";
import { CredentialReference, LoginCredential, ReviverFunc } from "./types.js";

/**
 * Read login credentials from the 1Password Credential Broker.
 * Accessed as `client.credential_broker.login` in the generated SDK bindings.
 */
export interface CredentialBrokerLoginApi {
  /**
   * Fetch the login credential identified by `credential_reference`.
   *
   * In addition to transport, keyset-decryption, and enclave errors surfaced as [Error::Internal],
   * fails with [Error::InvalidCredentialReference] if the reference is malformed
   * or does not name a login credential, or with [Error::CredentialReferenceAccountMismatch]
   * if it belongs to a different account than the authenticated client.
   */
  get(credentialReference: CredentialReference): Promise<LoginCredential>;
}

export class CredentialBrokerLogin implements CredentialBrokerLoginApi {
  #inner: InnerClient;

  public constructor(inner: InnerClient) {
    this.#inner = inner;
  }

  /**
   * Fetch the login credential identified by `credential_reference`.
   *
   * In addition to transport, keyset-decryption, and enclave errors surfaced as [Error::Internal],
   * fails with [Error::InvalidCredentialReference] if the reference is malformed
   * or does not name a login credential, or with [Error::CredentialReferenceAccountMismatch]
   * if it belongs to a different account than the authenticated client.
   */
  public async get(
    credentialReference: CredentialReference,
  ): Promise<LoginCredential> {
    const invocationConfig: InvokeConfig = {
      invocation: {
        clientId: this.#inner.id,
        parameters: {
          name: "CredentialBrokerLoginGet",
          parameters: {
            credential_reference: credentialReference,
          },
        },
      },
    };
    return JSON.parse(
      await this.#inner.invoke(invocationConfig),
      ReviverFunc,
    ) as LoginCredential;
  }
}
