// Code generated by op-codegen - DO NOT EDIT MANUALLY

import { InvokeConfig, InnerClient, SharedCore } from "./core.js";
import { ReviverFunc } from "./types.js";
import {
  CredentialBrokerEnvironmentApi,
  CredentialBrokerEnvironment,
} from "./credential_broker_environment.js";

/**
 * Root namespace for the 1Password Credential Broker.
 *
 * Marker trait — no methods of its own. Each supported credential kind is a
 * nested API accessed as `client.credential_broker.<kind>`
 * ([`Environment`] today; `Login`, `ApiKey`, ... as they land).
 */
export interface CredentialBrokerApi {
  environment: CredentialBrokerEnvironmentApi;
}

export class CredentialBroker implements CredentialBrokerApi {
  #inner: InnerClient;
  public environment: CredentialBrokerEnvironmentApi;

  public constructor(inner: InnerClient) {
    this.#inner = inner;
    this.environment = new CredentialBrokerEnvironment(inner);
  }
}
