// Code generated by op-codegen - DO NOT EDIT MANUALLY

import { InvokeConfig, InnerClient, SharedCore } from "./core.js";
import { LoginCredential, LoginDetails, ReviverFunc } from "./types.js";

/**
 * Read login credentials from the 1Password Credential Broker.
 * Accessed as `client.credential_broker.logins` in the generated SDK bindings.
 */
export interface CredentialBrokerLoginsApi {
  /**
   * Fetch the login credential identified by `credential_reference`.
   *
   * In addition to transport, keyset-decryption, and enclave errors surfaced as [Error::Internal],
   * fails with [Error::InvalidCredentialReference] if the reference is malformed
   * or does not name a login credential, or with [Error::CredentialReferenceAccountMismatch]
   * if it belongs to a different account than the authenticated client.
   */
  read(credentialReference: string): Promise<LoginCredential>;

  /**
   * Fetch non-secret details for the login identified by `credential_reference`.
   */
  getDetails(credentialReference: string): Promise<LoginDetails>;
}

export class CredentialBrokerLogins implements CredentialBrokerLoginsApi {
  #inner: InnerClient;

  public constructor(inner: InnerClient) {
    this.#inner = inner;
  }

  /**
   * Fetch the login credential identified by `credential_reference`.
   *
   * In addition to transport, keyset-decryption, and enclave errors surfaced as [Error::Internal],
   * fails with [Error::InvalidCredentialReference] if the reference is malformed
   * or does not name a login credential, or with [Error::CredentialReferenceAccountMismatch]
   * if it belongs to a different account than the authenticated client.
   */
  public async read(credentialReference: string): Promise<LoginCredential> {
    const invocationConfig: InvokeConfig = {
      invocation: {
        clientId: this.#inner.id,
        parameters: {
          name: "CredentialBrokerLoginsRead",
          parameters: {
            credential_reference: credentialReference,
          },
        },
      },
    };
    return JSON.parse(
      await this.#inner.invoke(invocationConfig),
      ReviverFunc,
    ) as LoginCredential;
  }

  /**
   * Fetch non-secret details for the login identified by `credential_reference`.
   */
  public async getDetails(credentialReference: string): Promise<LoginDetails> {
    const invocationConfig: InvokeConfig = {
      invocation: {
        clientId: this.#inner.id,
        parameters: {
          name: "CredentialBrokerLoginsGetDetails",
          parameters: {
            credential_reference: credentialReference,
          },
        },
      },
    };
    return JSON.parse(
      await this.#inner.invoke(invocationConfig),
      ReviverFunc,
    ) as LoginDetails;
  }
}
