// Code generated by op-codegen - DO NOT EDIT MANUALLY

import { InvokeConfig, InnerClient, SharedCore } from "./core.js";
import {
  AccessRequest,
  AccessRequestCreateParams,
  AccessRequestStatus,
  ReviverFunc,
} from "./types.js";

/**
 * Create and poll credential-broker access requests: asking a target
 * identity to grant this workload access to one or more credentials.
 *
 * Accessed as `client.credential_broker.access_requests` in the generated
 * SDK bindings.
 */
export interface CredentialBrokerAccessRequestsApi {
  /**
   * Register a new access request. The SDK mints the request id and
   * per-entry ids, and derives the target identity from the
   * authenticated workload.
   *
   * Only the non-sensitive half is registered server-side; the returned
   * request is the full object with the presentation fields re-attached.
   */
  create(params: AccessRequestCreateParams): Promise<AccessRequest>;

  /**
   * Get the current status of an access request created by
   * [`AccessRequests::create`].
   */
  getStatus(accessRequestId: string): Promise<AccessRequestStatus>;
}

export class CredentialBrokerAccessRequests
  implements CredentialBrokerAccessRequestsApi
{
  #inner: InnerClient;

  public constructor(inner: InnerClient) {
    this.#inner = inner;
  }

  /**
   * Register a new access request. The SDK mints the request id and
   * per-entry ids, and derives the target identity from the
   * authenticated workload.
   *
   * Only the non-sensitive half is registered server-side; the returned
   * request is the full object with the presentation fields re-attached.
   */
  public async create(
    params: AccessRequestCreateParams,
  ): Promise<AccessRequest> {
    const invocationConfig: InvokeConfig = {
      invocation: {
        clientId: this.#inner.id,
        parameters: {
          name: "CredentialBrokerAccessRequestsCreate",
          parameters: {
            params,
          },
        },
      },
    };
    return JSON.parse(
      await this.#inner.invoke(invocationConfig),
      ReviverFunc,
    ) as AccessRequest;
  }

  /**
   * Get the current status of an access request created by
   * [`AccessRequests::create`].
   */
  public async getStatus(
    accessRequestId: string,
  ): Promise<AccessRequestStatus> {
    const invocationConfig: InvokeConfig = {
      invocation: {
        clientId: this.#inner.id,
        parameters: {
          name: "CredentialBrokerAccessRequestsGetStatus",
          parameters: {
            access_request_id: accessRequestId,
          },
        },
      },
    };
    return JSON.parse(
      await this.#inner.invoke(invocationConfig),
      ReviverFunc,
    ) as AccessRequestStatus;
  }
}
