// Code generated by op-codegen - DO NOT EDIT MANUALLY

import { InvokeConfig, InnerClient, SharedCore } from "./core.js";
import {
  AccessRequest,
  AccessRequestCreateParams,
  AccessRequestStatus,
  ReviverFunc,
} from "./types.js";

/**
 * Create and poll credential-broker access requests: asking a target
 * identity to grant this workload access to one or more credentials.
 *
 * Accessed as `client.credential_broker.access_request` in the generated
 * SDK bindings.
 */
export interface CredentialBrokerAccessRequestApi {
  /**
   * Register a new access request. The SDK mints the request id and
   * per-entry ids, and derives the target identity from the
   * authenticated workload.
   *
   * Fails with [Error::InvalidConfiguration] if `params` doesn't hold
   * between 1 and 5 entries.
   */
  create(params: AccessRequestCreateParams): Promise<AccessRequest>;

  /**
   * Get the current status of an access request created by
   * [`AccessRequest::create`].
   */
  get(accessRequestId: string): Promise<AccessRequestStatus>;
}

export class CredentialBrokerAccessRequest
  implements CredentialBrokerAccessRequestApi
{
  #inner: InnerClient;

  public constructor(inner: InnerClient) {
    this.#inner = inner;
  }

  /**
   * Register a new access request. The SDK mints the request id and
   * per-entry ids, and derives the target identity from the
   * authenticated workload.
   *
   * Fails with [Error::InvalidConfiguration] if `params` doesn't hold
   * between 1 and 5 entries.
   */
  public async create(
    params: AccessRequestCreateParams,
  ): Promise<AccessRequest> {
    const invocationConfig: InvokeConfig = {
      invocation: {
        clientId: this.#inner.id,
        parameters: {
          name: "CredentialBrokerAccessRequestCreate",
          parameters: {
            params,
          },
        },
      },
    };
    return JSON.parse(
      await this.#inner.invoke(invocationConfig),
      ReviverFunc,
    ) as AccessRequest;
  }

  /**
   * Get the current status of an access request created by
   * [`AccessRequest::create`].
   */
  public async get(accessRequestId: string): Promise<AccessRequestStatus> {
    const invocationConfig: InvokeConfig = {
      invocation: {
        clientId: this.#inner.id,
        parameters: {
          name: "CredentialBrokerAccessRequestGet",
          parameters: {
            access_request_id: accessRequestId,
          },
        },
      },
    };
    return JSON.parse(
      await this.#inner.invoke(invocationConfig),
      ReviverFunc,
    ) as AccessRequestStatus;
  }
}
