// Code generated by op-codegen - DO NOT EDIT MANUALLY

import { InvokeConfig, InnerClient, SharedCore } from "./core.js";
import { ReviverFunc } from "./types.js";
import {
  CredentialBrokerEnvironmentVariablesApi,
  CredentialBrokerEnvironmentVariables,
} from "./credential_broker_environment_variables.js";
import {
  CredentialBrokerLoginsApi,
  CredentialBrokerLogins,
} from "./credential_broker_logins.js";
import {
  CredentialBrokerAccessRequestsApi,
  CredentialBrokerAccessRequests,
} from "./credential_broker_access_requests.js";

/**
 * Root namespace for the 1Password Credential Broker.
 *
 * Marker trait — no methods of its own. Each supported credential kind is a
 * nested API accessed as `client.credential_broker.<kind>`
 * ([`EnvironmentVariables`] and [`Logins`] today; `ApiKey`, ... as they land).
 */
export interface CredentialBrokerApi {
  environmentVariables: CredentialBrokerEnvironmentVariablesApi;
  logins: CredentialBrokerLoginsApi;
}

export class CredentialBroker implements CredentialBrokerApi {
  #inner: InnerClient;
  public environmentVariables: CredentialBrokerEnvironmentVariablesApi;
  public logins: CredentialBrokerLoginsApi;

  public constructor(inner: InnerClient) {
    this.#inner = inner;
    this.environmentVariables = new CredentialBrokerEnvironmentVariables(inner);
    this.logins = new CredentialBrokerLogins(inner);
  }
}

export interface OAuthCredentialBrokerApi extends CredentialBrokerApi {
  accessRequests: CredentialBrokerAccessRequestsApi;
}

export class OAuthCredentialBroker
  extends CredentialBroker
  implements OAuthCredentialBrokerApi
{
  public accessRequests: CredentialBrokerAccessRequestsApi;

  public constructor(inner: InnerClient) {
    super(inner);
    this.accessRequests = new CredentialBrokerAccessRequests(inner);
  }
}
