// Code generated by op-codegen - DO NOT EDIT MANUALLY

import { InvokeConfig, InnerClient, SharedCore } from "./core.js";
import {
  Environment,
  EnvironmentSecret,
  GetVariablesResponse,
  ReviverFunc,
} from "./types.js";

/**
 * The Environments API holds all the operations the SDK client can perform
 * on 1Password Environments and the secrets inside them.
 */
export interface EnvironmentsApi {
  /**
   * Get environment variables belonging to an Environment.
   */
  getVariables(environmentId: string): Promise<GetVariablesResponse>;

  /**
   * Get a single secret from an Environment.
   *
   * `environment_name_id` accepts either the Environment's name or its
   * ID; a name that matches more than one Environment is an error.
   *
   * `secret_name` is the name of the secret to get, matched
   * case-insensitively; a name that matches more than one secret in the
   * Environment is an error.
   *
   * `reveal` controls whether a concealed secret's value is returned;
   * when `reveal` is `false`, a concealed value is withheld.
   */
  getSecret(
    environmentNameId: string,
    secretName: string,
    reveal: boolean,
  ): Promise<EnvironmentSecret>;

  /**
   * List all secrets in an Environment.
   *
   * `environment_name_id` accepts either the Environment's name or its
   * ID; a name that matches more than one Environment is an error.
   *
   * `reveal` controls whether concealed secrets' values are returned;
   * when `reveal` is `false`, concealed values are withheld.
   */
  listSecrets(
    environmentNameId: string,
    reveal: boolean,
  ): Promise<EnvironmentSecret[]>;

  /**
   * Create a new Environment.
   *
   * `environment_name` accepts a name for the new Environment. The name is
   * trimmed. A name that is empty after trimming is an error.
   */
  create(environmentName: string): Promise<Environment>;
}

export class Environments implements EnvironmentsApi {
  #inner: InnerClient;

  public constructor(inner: InnerClient) {
    this.#inner = inner;
  }

  /**
   * Get environment variables belonging to an Environment.
   */
  public async getVariables(
    environmentId: string,
  ): Promise<GetVariablesResponse> {
    const invocationConfig: InvokeConfig = {
      invocation: {
        clientId: this.#inner.id,
        parameters: {
          name: "EnvironmentsGetVariables",
          parameters: {
            environment_id: environmentId,
          },
        },
      },
    };
    return JSON.parse(
      await this.#inner.invoke(invocationConfig),
      ReviverFunc,
    ) as GetVariablesResponse;
  }

  /**
   * Get a single secret from an Environment.
   *
   * `environment_name_id` accepts either the Environment's name or its
   * ID; a name that matches more than one Environment is an error.
   *
   * `secret_name` is the name of the secret to get, matched
   * case-insensitively; a name that matches more than one secret in the
   * Environment is an error.
   *
   * `reveal` controls whether a concealed secret's value is returned;
   * when `reveal` is `false`, a concealed value is withheld.
   */
  public async getSecret(
    environmentNameId: string,
    secretName: string,
    reveal: boolean,
  ): Promise<EnvironmentSecret> {
    const invocationConfig: InvokeConfig = {
      invocation: {
        clientId: this.#inner.id,
        parameters: {
          name: "EnvironmentsGetSecret",
          parameters: {
            environment_name_id: environmentNameId,
            secret_name: secretName,
            reveal,
          },
        },
      },
    };
    return JSON.parse(
      await this.#inner.invoke(invocationConfig),
      ReviverFunc,
    ) as EnvironmentSecret;
  }

  /**
   * List all secrets in an Environment.
   *
   * `environment_name_id` accepts either the Environment's name or its
   * ID; a name that matches more than one Environment is an error.
   *
   * `reveal` controls whether concealed secrets' values are returned;
   * when `reveal` is `false`, concealed values are withheld.
   */
  public async listSecrets(
    environmentNameId: string,
    reveal: boolean,
  ): Promise<EnvironmentSecret[]> {
    const invocationConfig: InvokeConfig = {
      invocation: {
        clientId: this.#inner.id,
        parameters: {
          name: "EnvironmentsListSecrets",
          parameters: {
            environment_name_id: environmentNameId,
            reveal,
          },
        },
      },
    };
    return JSON.parse(
      await this.#inner.invoke(invocationConfig),
      ReviverFunc,
    ) as EnvironmentSecret[];
  }

  /**
   * Create a new Environment.
   *
   * `environment_name` accepts a name for the new Environment. The name is
   * trimmed. A name that is empty after trimming is an error.
   */
  public async create(environmentName: string): Promise<Environment> {
    const invocationConfig: InvokeConfig = {
      invocation: {
        clientId: this.#inner.id,
        parameters: {
          name: "EnvironmentsCreate",
          parameters: {
            environment_name: environmentName,
          },
        },
      },
    };
    return JSON.parse(
      await this.#inner.invoke(invocationConfig),
      ReviverFunc,
    ) as Environment;
  }
}
