// Code generated by op-codegen - DO NOT EDIT MANUALLY

import { InvokeConfig, InnerClient } from "./core.js";
import { GetVariablesResponse, ReviverFunc } from "./types.js";

/**
 * The Environments API holds all the operations the SDK client can perform on 1Password Environments (Vault Type = 'D').
 */
export interface EnvironmentsApi {
  /**
   * Get environment variables belonging to an Environment.
   */
  getVariables(environmentId: string): Promise<GetVariablesResponse>;
}

export class Environments implements EnvironmentsApi {
  #inner: InnerClient;

  public constructor(inner: InnerClient) {
    this.#inner = inner;
  }

  /**
   * Get environment variables belonging to an Environment.
   */
  public async getVariables(
    environmentId: string,
  ): Promise<GetVariablesResponse> {
    const invocationConfig: InvokeConfig = {
      invocation: {
        clientId: this.#inner.id,
        parameters: {
          name: "EnvironmentsGetVariables",
          parameters: {
            environment_id: environmentId,
          },
        },
      },
    };
    return JSON.parse(
      await this.#inner.invoke(invocationConfig),
      ReviverFunc,
    ) as GetVariablesResponse;
  }
}
