// Code generated by op-codegen - DO NOT EDIT MANUALLY

export class RateLimitExceededError extends Error {
  public message: string;

  public constructor(message: string) {
    super();
    this.message = message;
  }
}

export const throwError = (errString: string) => {
  interface TypedError {
    name: string;
    message: string;
  }

  let err: TypedError;
  try {
    err = JSON.parse(errString) as TypedError;
  } catch (e) {
    throw new Error(errString);
  }

  switch (err.name) {
    case "RateLimitExceeded":
      throw new RateLimitExceededError(err.message);
    default:
      throw new Error(err.message);
  }
}
