// Code generated by op-codegen - DO NOT EDIT MANUALLY

import { InvokeConfig, InnerClient, SharedCore } from "./core.js";
import { Group, GroupGetParams, ReviverFunc } from "./types.js";

/**
 * The Groups API holds all the operations the SDK client can perform on 1Password groups.
 */
export interface GroupsApi {
  get(groupId: string, groupParams: GroupGetParams): Promise<Group>;
}

export class Groups implements GroupsApi {
  #inner: InnerClient;

  public constructor(inner: InnerClient) {
    this.#inner = inner;
  }

  public async get(
    groupId: string,
    groupParams: GroupGetParams,
  ): Promise<Group> {
    const invocationConfig: InvokeConfig = {
      invocation: {
        clientId: this.#inner.id,
        parameters: {
          name: "GroupsGet",
          parameters: {
            group_id: groupId,
            group_params: groupParams,
          },
        },
      },
    };
    return JSON.parse(
      await this.#inner.core.invoke(invocationConfig),
      ReviverFunc,
    ) as Group;
  }
}
