// Code generated by op-codegen - DO NOT EDIT MANUALLY

import { InvokeConfig, InnerClient, SharedCore } from "./core.js";
import * as types from "./types.js";
import { SdkIterable } from "./iterator.js";

export interface ItemsSharesApi {
  /**
   * Get the item sharing policy of your account.
   */
  getAccountPolicy(
    vaultId: string,
    itemId: string,
  ): Promise<types.ItemShareAccountPolicy>;

  /**
   * Validate the recipients of an item sharing link.
   */
  validateRecipients(
    policy: types.ItemShareAccountPolicy,
    recipients: string[],
  ): Promise<types.ValidRecipient[]>;

  /**
   * Create a new item sharing link.
   */
  create(
    item: types.Item,
    policy: types.ItemShareAccountPolicy,
    params: types.ItemShareParams,
  ): Promise<string>;
}

export class ItemsShares implements ItemsSharesApi {
  #inner: InnerClient;

  public constructor(inner: InnerClient) {
    this.#inner = inner;
  }

  /**
   * Get the item sharing policy of your account.
   */
  public async getAccountPolicy(
    vaultId: string,
    itemId: string,
  ): Promise<types.ItemShareAccountPolicy> {
    const invocationConfig: InvokeConfig = {
      invocation: {
        clientId: this.#inner.id,
        parameters: {
          name: "ItemsSharesGetAccountPolicy",
          parameters: {
            vault_id: vaultId,
            item_id: itemId,
          },
        },
      },
    };
    return JSON.parse(
      await this.#inner.core.invoke(invocationConfig),
    ) as Promise<types.ItemShareAccountPolicy>;
  }

  /**
   * Validate the recipients of an item sharing link.
   */
  public async validateRecipients(
    policy: types.ItemShareAccountPolicy,
    recipients: string[],
  ): Promise<types.ValidRecipient[]> {
    const invocationConfig: InvokeConfig = {
      invocation: {
        clientId: this.#inner.id,
        parameters: {
          name: "ItemsSharesValidateRecipients",
          parameters: {
            policy,
            recipients,
          },
        },
      },
    };
    return JSON.parse(
      await this.#inner.core.invoke(invocationConfig),
    ) as Promise<types.ValidRecipient[]>;
  }

  /**
   * Create a new item sharing link.
   */
  public async create(
    item: types.Item,
    policy: types.ItemShareAccountPolicy,
    params: types.ItemShareParams,
  ): Promise<string> {
    const invocationConfig: InvokeConfig = {
      invocation: {
        clientId: this.#inner.id,
        parameters: {
          name: "ItemsSharesCreate",
          parameters: {
            item,
            policy,
            params,
          },
        },
      },
    };
    return JSON.parse(
      await this.#inner.core.invoke(invocationConfig),
    ) as Promise<string>;
  }
}
