// Code generated by op-codegen - DO NOT EDIT MANUALLY

import { InvokeConfig, InnerClient, SharedCore } from "./core.js";
import {
  Item,
  ItemCreateParams,
  ItemListFilter,
  ItemOverview,
  ItemsDeleteAllResponse,
  ItemsGetAllResponse,
  ItemsUpdateAllResponse,
  ReviverFunc,
} from "./types.js";
import { ItemsSharesApi, ItemsShares } from "./items_shares.js";
import { ItemsFilesApi, ItemsFiles } from "./items_files.js";

/**
 * The Items API holds all operations the SDK client can perform on 1Password items.
 */
export interface ItemsApi {
  shares: ItemsSharesApi;
  files: ItemsFilesApi;
  /**
   * Create a new item.
   */
  create(params: ItemCreateParams): Promise<Item>;

  /**
   * Create items in batch, within a single vault.
   */
  createAll(
    vaultId: string,
    params: ItemCreateParams[],
  ): Promise<ItemsUpdateAllResponse>;

  /**
   * Get an item by vault and item ID
   */
  get(vaultId: string, itemId: string): Promise<Item>;

  /**
   * Get items by vault and their item IDs.
   */
  getAll(vaultId: string, itemIds: string[]): Promise<ItemsGetAllResponse>;

  /**
   * Update an existing item.
   */
  put(item: Item): Promise<Item>;

  /**
   * Delete an item.
   */
  delete(vaultId: string, itemId: string);

  /**
   * Delete items in batch, within a single vault.
   */
  deleteAll(
    vaultId: string,
    itemIds: string[],
  ): Promise<ItemsDeleteAllResponse>;

  /**
   * Archive an item.
   */
  archive(vaultId: string, itemId: string);

  /**
   * List items based on filters.
   */
  list(vaultId: string, ...filters: ItemListFilter[]): Promise<ItemOverview[]>;
}

export class Items implements ItemsApi {
  #inner: InnerClient;
  public shares: ItemsSharesApi;
  public files: ItemsFilesApi;

  public constructor(inner: InnerClient) {
    this.#inner = inner;
    this.shares = new ItemsShares(inner);
    this.files = new ItemsFiles(inner);
  }

  /**
   * Create a new item.
   */
  public async create(params: ItemCreateParams): Promise<Item> {
    const invocationConfig: InvokeConfig = {
      invocation: {
        clientId: this.#inner.id,
        parameters: {
          name: "ItemsCreate",
          parameters: {
            params,
          },
        },
      },
    };
    return JSON.parse(
      await this.#inner.core.invoke(invocationConfig),
      ReviverFunc,
    ) as Item;
  }

  /**
   * Create items in batch, within a single vault.
   */
  public async createAll(
    vaultId: string,
    params: ItemCreateParams[],
  ): Promise<ItemsUpdateAllResponse> {
    const invocationConfig: InvokeConfig = {
      invocation: {
        clientId: this.#inner.id,
        parameters: {
          name: "ItemsCreateAll",
          parameters: {
            vault_id: vaultId,
            params,
          },
        },
      },
    };
    return JSON.parse(
      await this.#inner.core.invoke(invocationConfig),
      ReviverFunc,
    ) as ItemsUpdateAllResponse;
  }

  /**
   * Get an item by vault and item ID
   */
  public async get(vaultId: string, itemId: string): Promise<Item> {
    const invocationConfig: InvokeConfig = {
      invocation: {
        clientId: this.#inner.id,
        parameters: {
          name: "ItemsGet",
          parameters: {
            vault_id: vaultId,
            item_id: itemId,
          },
        },
      },
    };
    return JSON.parse(
      await this.#inner.core.invoke(invocationConfig),
      ReviverFunc,
    ) as Item;
  }

  /**
   * Get items by vault and their item IDs.
   */
  public async getAll(
    vaultId: string,
    itemIds: string[],
  ): Promise<ItemsGetAllResponse> {
    const invocationConfig: InvokeConfig = {
      invocation: {
        clientId: this.#inner.id,
        parameters: {
          name: "ItemsGetAll",
          parameters: {
            vault_id: vaultId,
            item_ids: itemIds,
          },
        },
      },
    };
    return JSON.parse(
      await this.#inner.core.invoke(invocationConfig),
      ReviverFunc,
    ) as ItemsGetAllResponse;
  }

  /**
   * Update an existing item.
   */
  public async put(item: Item): Promise<Item> {
    const invocationConfig: InvokeConfig = {
      invocation: {
        clientId: this.#inner.id,
        parameters: {
          name: "ItemsPut",
          parameters: {
            item,
          },
        },
      },
    };
    return JSON.parse(
      await this.#inner.core.invoke(invocationConfig),
      ReviverFunc,
    ) as Item;
  }

  /**
   * Delete an item.
   */
  public async delete(vaultId: string, itemId: string) {
    const invocationConfig: InvokeConfig = {
      invocation: {
        clientId: this.#inner.id,
        parameters: {
          name: "ItemsDelete",
          parameters: {
            vault_id: vaultId,
            item_id: itemId,
          },
        },
      },
    };
    await this.#inner.core.invoke(invocationConfig);
  }

  /**
   * Delete items in batch, within a single vault.
   */
  public async deleteAll(
    vaultId: string,
    itemIds: string[],
  ): Promise<ItemsDeleteAllResponse> {
    const invocationConfig: InvokeConfig = {
      invocation: {
        clientId: this.#inner.id,
        parameters: {
          name: "ItemsDeleteAll",
          parameters: {
            vault_id: vaultId,
            item_ids: itemIds,
          },
        },
      },
    };
    return JSON.parse(
      await this.#inner.core.invoke(invocationConfig),
      ReviverFunc,
    ) as ItemsDeleteAllResponse;
  }

  /**
   * Archive an item.
   */
  public async archive(vaultId: string, itemId: string) {
    const invocationConfig: InvokeConfig = {
      invocation: {
        clientId: this.#inner.id,
        parameters: {
          name: "ItemsArchive",
          parameters: {
            vault_id: vaultId,
            item_id: itemId,
          },
        },
      },
    };
    await this.#inner.core.invoke(invocationConfig);
  }

  /**
   * List items based on filters.
   */
  public async list(
    vaultId: string,
    ...filters: ItemListFilter[]
  ): Promise<ItemOverview[]> {
    const invocationConfig: InvokeConfig = {
      invocation: {
        clientId: this.#inner.id,
        parameters: {
          name: "ItemsList",
          parameters: {
            vault_id: vaultId,
            filters,
          },
        },
      },
    };
    return JSON.parse(
      await this.#inner.core.invoke(invocationConfig),
      ReviverFunc,
    ) as ItemOverview[];
  }
}
