// Code generated by op-codegen - DO NOT EDIT MANUALLY

import { InvokeConfig, InnerClient, SharedCore } from "./core.js";
import {
  DocumentCreateParams,
  FileAttributes,
  FileCreateParams,
  Item,
  ReviverFunc,
} from "./types.js";

export interface ItemsFilesApi {
  /**
   * Attach files to Items
   */
  attach(item: Item, fileParams: FileCreateParams): Promise<Item>;

  /**
   * Read file content from the Item
   */
  read(
    vaultId: string,
    itemId: string,
    attr: FileAttributes,
  ): Promise<Uint8Array>;

  /**
   * Delete a field file from Item using the section and field IDs
   */
  delete(item: Item, sectionId: string, fieldId: string): Promise<Item>;

  /**
   * Replace the document file within a document item
   */
  replaceDocument(item: Item, docParams: DocumentCreateParams): Promise<Item>;
}

export class ItemsFiles implements ItemsFilesApi {
  #inner: InnerClient;

  public constructor(inner: InnerClient) {
    this.#inner = inner;
  }

  /**
   * Attach files to Items
   */
  public async attach(item: Item, fileParams: FileCreateParams): Promise<Item> {
    const invocationConfig: InvokeConfig = {
      invocation: {
        clientId: this.#inner.id,
        parameters: {
          name: "ItemsFilesAttach",
          parameters: {
            item,
            file_params: fileParams,
          },
        },
      },
    };
    return JSON.parse(
      await this.#inner.core.invoke(invocationConfig),
      ReviverFunc,
    ) as Item;
  }

  /**
   * Read file content from the Item
   */
  public async read(
    vaultId: string,
    itemId: string,
    attr: FileAttributes,
  ): Promise<Uint8Array> {
    const invocationConfig: InvokeConfig = {
      invocation: {
        clientId: this.#inner.id,
        parameters: {
          name: "ItemsFilesRead",
          parameters: {
            vault_id: vaultId,
            item_id: itemId,
            attr,
          },
        },
      },
    };
    return JSON.parse(
      await this.#inner.core.invoke(invocationConfig),
      ReviverFunc,
    ) as Uint8Array;
  }

  /**
   * Delete a field file from Item using the section and field IDs
   */
  public async delete(
    item: Item,
    sectionId: string,
    fieldId: string,
  ): Promise<Item> {
    const invocationConfig: InvokeConfig = {
      invocation: {
        clientId: this.#inner.id,
        parameters: {
          name: "ItemsFilesDelete",
          parameters: {
            item,
            section_id: sectionId,
            field_id: fieldId,
          },
        },
      },
    };
    return JSON.parse(
      await this.#inner.core.invoke(invocationConfig),
      ReviverFunc,
    ) as Item;
  }

  /**
   * Replace the document file within a document item
   */
  public async replaceDocument(
    item: Item,
    docParams: DocumentCreateParams,
  ): Promise<Item> {
    const invocationConfig: InvokeConfig = {
      invocation: {
        clientId: this.#inner.id,
        parameters: {
          name: "ItemsFilesReplaceDocument",
          parameters: {
            item,
            doc_params: docParams,
          },
        },
      },
    };
    return JSON.parse(
      await this.#inner.core.invoke(invocationConfig),
      ReviverFunc,
    ) as Item;
  }
}
