// Code generated by op-codegen - DO NOT EDIT MANUALLY

import { SharedCore } from "./core.js";
import { ClientConfiguration } from "./configuration.js";
import { Client } from "./client.js";
import { createClientWithCore } from "./client_builder.js";

export const DEFAULT_INTEGRATION_NAME = "Unknown";
export const DEFAULT_INTEGRATION_VERSION = "Unknown";

// auto-generated static exports
export { Secrets } from "./secrets.js";
export { DesktopAuth } from "./configuration.js";

export * from "./client.js";
export * from "./errors.js";
export * from "./types.js";

/**
 * Creates a default 1Password SDK client.
 * @returns The authenticated 1Password SDK client.
 */
export const createClient = async (
  config: ClientConfiguration,
): Promise<Client> => createClientWithCore(config, new SharedCore());

import {
  OAuthClientConfiguration,
  WorkloadClientConfiguration,
} from "./configuration.js";
import { WorkloadClient } from "./client.js";
import { createWorkloadClientWithCore } from "./client_builder.js";

/**
 * Creates a 1Password broker client authenticated as either a workload or an
 * OAuth integration.
 * @returns The authenticated 1Password broker client.
 */
export const createWorkloadClient = async (
  config: WorkloadClientConfiguration | OAuthClientConfiguration,
): Promise<WorkloadClient> =>
  createWorkloadClientWithCore(config, new SharedCore());
