// Code generated by op-codegen - DO NOT EDIT MANUALLY

import { SharedCore } from "./core.js";
import {
  ClientConfiguration,
  OidcClientConfiguration,
  OAuthClientConfiguration,
} from "./configuration.js";
import { Client, OidcClient, OAuthClient } from "./client.js";
import {
  createClientWithCore,
  createOidcClientWithCore,
  createOAuthClientWithCore,
} from "./client_builder.js";

export const DEFAULT_INTEGRATION_NAME = "Unknown";
export const DEFAULT_INTEGRATION_VERSION = "Unknown";

// auto-generated static exports
export { Secrets } from "./secrets.js";
export { DesktopAuth } from "./configuration.js";

export * from "./client.js";
export * from "./errors.js";
export * from "./types.js";

/**
 * Creates a default 1Password SDK client.
 * @returns The authenticated 1Password SDK client.
 */
export const createClient = async (
  config: ClientConfiguration,
): Promise<Client> => createClientWithCore(config, new SharedCore());

/**
 * Creates a 1Password OIDC client, authenticated through the workload-identity init path.
 * @returns The authenticated 1Password OIDC client.
 */
export const createOidcClient = async (
  config: OidcClientConfiguration,
): Promise<OidcClient> => createOidcClientWithCore(config, new SharedCore());

/**
 * Creates a 1Password OAuth client, authenticated with the credentials returned by the OAuth flow.
 * @returns The authenticated 1Password OAuth client.
 */
export const createOAuthClient = async (
  config: OAuthClientConfiguration,
): Promise<OAuthClient> => createOAuthClientWithCore(config, new SharedCore());
