// Code generated by op-codegen - DO NOT EDIT MANUALLY

import { SharedCore } from "./core.js";
import {
  ClientConfiguration,
  OAuthClientConfiguration,
  WorkloadClientConfiguration,
} from "./configuration.js";
import { Client, OAuthClient, WorkloadClient } from "./client.js";
import {
  createClientWithCore,
  createOAuthClientWithCore,
  createWorkloadClientWithCore,
} from "./client_builder.js";

export const DEFAULT_INTEGRATION_NAME = "Unknown";
export const DEFAULT_INTEGRATION_VERSION = "Unknown";

// auto-generated static exports
export { Secrets } from "./secrets.js";
export { DesktopAuth } from "./configuration.js";

export * from "./client.js";
export * from "./errors.js";
export * from "./types.js";

/**
 * Creates a default 1Password SDK client.
 * @returns The authenticated 1Password SDK client.
 */
export const createClient = async (
  config: ClientConfiguration,
): Promise<Client> => createClientWithCore(config, new SharedCore());

/**
 * Creates a 1Password workload client through the workload-identity init path.
 * @returns The authenticated 1Password workload client.
 */
export const createWorkloadClient = async (
  config: WorkloadClientConfiguration,
): Promise<WorkloadClient> =>
  createWorkloadClientWithCore(config, new SharedCore());

/**
 * Creates a 1Password OAuth client.
 * @returns The authenticated 1Password OAuth client.
 */
export const createOAuthClient = async (
  config: OAuthClientConfiguration,
): Promise<OAuthClient> => createOAuthClientWithCore(config, new SharedCore());
