// Code generated by op-codegen - DO NOT EDIT MANUALLY

import { InvokeConfig, InnerClient, SharedCore } from "./core.js";
import {
  GeneratePasswordResponse,
  PasswordRecipe,
  ResolveAllResponse,
  ReviverFunc,
} from "./types.js";

/**
 * The Secrets API includes all operations the SDK client can perform on secrets.
 * Use secret reference URIs to securely load secrets from 1Password: op://<vault-name>/<item-name>[/<section-name>]/<field-name>
 */
export interface SecretsApi {
  /**
   * Resolve returns the secret the provided secret reference points to.
   */
  resolve(secretReference: string): Promise<string>;

  /**
   * Resolve takes in a list of secret references and returns the secrets they point to or errors if any.
   */
  resolveAll(secretReferences: string[]): Promise<ResolveAllResponse>;
}

export class Secrets implements SecretsApi {
  #inner: InnerClient;

  public constructor(inner: InnerClient) {
    this.#inner = inner;
  }

  /**
   * Resolve returns the secret the provided secret reference points to.
   */
  public async resolve(secretReference: string): Promise<string> {
    const invocationConfig: InvokeConfig = {
      invocation: {
        clientId: this.#inner.id,
        parameters: {
          name: "SecretsResolve",
          parameters: {
            secret_reference: secretReference,
          },
        },
      },
    };
    return JSON.parse(
      await this.#inner.core.invoke(invocationConfig),
      ReviverFunc,
    ) as string;
  }

  /**
   * Resolve takes in a list of secret references and returns the secrets they point to or errors if any.
   */
  public async resolveAll(
    secretReferences: string[],
  ): Promise<ResolveAllResponse> {
    const invocationConfig: InvokeConfig = {
      invocation: {
        clientId: this.#inner.id,
        parameters: {
          name: "SecretsResolveAll",
          parameters: {
            secret_references: secretReferences,
          },
        },
      },
    };
    return JSON.parse(
      await this.#inner.core.invoke(invocationConfig),
      ReviverFunc,
    ) as ResolveAllResponse;
  }

  /**
   * Validate the secret reference to ensure there are no syntax errors.
   */
  public static validateSecretReference(secretReference: string) {
    const sharedCore = new SharedCore();
    const invocationConfig: InvokeConfig = {
      invocation: {
        parameters: {
          name: "ValidateSecretReference",
          parameters: {
            secret_reference: secretReference,
          },
        },
      },
    };
    sharedCore.invoke_sync(invocationConfig);
  }

  public static generatePassword(
    recipe: PasswordRecipe,
  ): GeneratePasswordResponse {
    const sharedCore = new SharedCore();
    const invocationConfig: InvokeConfig = {
      invocation: {
        parameters: {
          name: "GeneratePassword",
          parameters: {
            recipe,
          },
        },
      },
    };
    return JSON.parse(
      sharedCore.invoke_sync(invocationConfig),
      ReviverFunc,
    ) as GeneratePasswordResponse;
  }
}
