/*
 Generated by typeshare 1.9.0
*/

export interface AccountOverview {
  user_count: number;
  group_count: number;
  vault_count: number;
}

export interface DeviceClientOverview {
  client_name: string;
  count: number;
}

export interface DevicesOverview {
  clients: DeviceClientOverview[];
}
