/*
 Generated by typeshare 1.9.2
*/

export enum ItemCategory {
  Login = "Login",
  SecureNote = "SecureNote",
  CreditCard = "CreditCard",
  CryptoWallet = "CryptoWallet",
  Identity = "Identity",
  Password = "Password",
  Document = "Document",
  ApiCredentials = "ApiCredentials",
  BankAccount = "BankAccount",
  Database = "Database",
  DriverLicense = "DriverLicense",
  Email = "Email",
  MedicalRecord = "MedicalRecord",
  Membership = "Membership",
  OutdoorLicense = "OutdoorLicense",
  Passport = "Passport",
  Rewards = "Rewards",
  Router = "Router",
  Server = "Server",
  SshKey = "SshKey",
  SocialSecurityNumber = "SocialSecurityNumber",
  SoftwareLicense = "SoftwareLicense",
  Person = "Person",
  Unsupported = "Unsupported",
}

export enum ItemFieldType {
  Text = "Text",
  Concealed = "Concealed",
  Unsupported = "Unsupported",
}

/** Represents a field within an item. */
export interface ItemField {
  /** The field's ID */
  id: string;
  /** The field's title */
  title: string;
  /** The ID of the section containing the field. Built-in fields such as usernames and passwords don't require a section. */
  section_id?: string;
  /** The field's type */
  field_type: ItemFieldType;
  /** The string representation of the field's value */
  value: string;
}

/** A section groups together multiple fields in an item. */
export interface ItemSection {
  /** The section's unique ID */
  id: string;
  /** The section's title */
  title: string;
}

/** Represents a 1Password item. */
export interface Item {
  /** The item's ID */
  id: string;
  /** The item's title */
  title: string;
  /** The item's category */
  category: ItemCategory;
  /** The ID of the vault where the item is saved */
  vault_id: string;
  /** The item's fields */
  fields: ItemField[];
  /** The item's sections */
  sections: ItemSection[];
}
