// Code generated by op-codegen - DO NOT EDIT MANUALLY

import { InvokeConfig, InnerClient, SharedCore } from "./core.js";
import {
  GroupAccess,
  GroupVaultAccess,
  Vault,
  VaultGetParams,
  VaultListParams,
  VaultOverview,
  ReviverFunc,
} from "./types.js";

/**
 * The Vaults API holds all the operations the SDK client can perform on 1Password vaults.
 */
export interface VaultsApi {
  /**
   * List information about vaults that's configurable based on some input parameters.
   */
  list(params?: VaultListParams): Promise<VaultOverview[]>;

  getOverview(vaultUuid: string): Promise<VaultOverview>;

  get(vaultUuid: string, vaultParams: VaultGetParams): Promise<Vault>;

  grantGroupPermissions(vaultId: string, groupPermissionsList: GroupAccess[]);

  updateGroupPermissions(groupPermissionsList: GroupVaultAccess[]);

  revokeGroupPermissions(vaultId: string, groupId: string);
}

export class Vaults implements VaultsApi {
  #inner: InnerClient;

  public constructor(inner: InnerClient) {
    this.#inner = inner;
  }

  /**
   * List information about vaults that's configurable based on some input parameters.
   */
  public async list(params: VaultListParams): Promise<VaultOverview[]> {
    const invocationConfig: InvokeConfig = {
      invocation: {
        clientId: this.#inner.id,
        parameters: {
          name: "VaultsList",
          parameters: {
            params,
          },
        },
      },
    };
    return JSON.parse(
      await this.#inner.core.invoke(invocationConfig),
      ReviverFunc,
    ) as VaultOverview[];
  }

  public async getOverview(vaultUuid: string): Promise<VaultOverview> {
    const invocationConfig: InvokeConfig = {
      invocation: {
        clientId: this.#inner.id,
        parameters: {
          name: "VaultsGetOverview",
          parameters: {
            vault_uuid: vaultUuid,
          },
        },
      },
    };
    return JSON.parse(
      await this.#inner.core.invoke(invocationConfig),
      ReviverFunc,
    ) as VaultOverview;
  }

  public async get(
    vaultUuid: string,
    vaultParams: VaultGetParams,
  ): Promise<Vault> {
    const invocationConfig: InvokeConfig = {
      invocation: {
        clientId: this.#inner.id,
        parameters: {
          name: "VaultsGet",
          parameters: {
            vault_uuid: vaultUuid,
            vault_params: vaultParams,
          },
        },
      },
    };
    return JSON.parse(
      await this.#inner.core.invoke(invocationConfig),
      ReviverFunc,
    ) as Vault;
  }

  public async grantGroupPermissions(
    vaultId: string,
    groupPermissionsList: GroupAccess[],
  ) {
    const invocationConfig: InvokeConfig = {
      invocation: {
        clientId: this.#inner.id,
        parameters: {
          name: "VaultsGrantGroupPermissions",
          parameters: {
            vault_id: vaultId,
            group_permissions_list: groupPermissionsList,
          },
        },
      },
    };
    await this.#inner.core.invoke(invocationConfig);
  }

  public async updateGroupPermissions(
    groupPermissionsList: GroupVaultAccess[],
  ) {
    const invocationConfig: InvokeConfig = {
      invocation: {
        clientId: this.#inner.id,
        parameters: {
          name: "VaultsUpdateGroupPermissions",
          parameters: {
            group_permissions_list: groupPermissionsList,
          },
        },
      },
    };
    await this.#inner.core.invoke(invocationConfig);
  }

  public async revokeGroupPermissions(vaultId: string, groupId: string) {
    const invocationConfig: InvokeConfig = {
      invocation: {
        clientId: this.#inner.id,
        parameters: {
          name: "VaultsRevokeGroupPermissions",
          parameters: {
            vault_id: vaultId,
            group_id: groupId,
          },
        },
      },
    };
    await this.#inner.core.invoke(invocationConfig);
  }
}
