// Code generated by op-codegen - DO NOT EDIT MANUALLY

import { InvokeConfig, InnerClient, SharedCore } from "./core.js";
import { VaultOverview, ReviverFunc } from "./types.js";

/**
 * The Vaults API holds all the operations the SDK client can perform on 1Password vaults.
 */
export interface VaultsApi {
  /**
   * List all vaults
   */
  list(): Promise<VaultOverview[]>;
}

export class Vaults implements VaultsApi {
  #inner: InnerClient;

  public constructor(inner: InnerClient) {
    this.#inner = inner;
  }

  /**
   * List all vaults
   */
  public async list(): Promise<VaultOverview[]> {
    const invocationConfig: InvokeConfig = {
      invocation: {
        clientId: this.#inner.id,
        parameters: {
          name: "VaultsList",
          parameters: {},
        },
      },
    };
    return JSON.parse(
      await this.#inner.core.invoke(invocationConfig),
      ReviverFunc,
    ) as VaultOverview[];
  }
}
