// Code generated by op-codegen - DO NOT EDIT MANUALLY

import { InvokeConfig, InnerClient, SharedCore } from "./core.js";
import {
  GroupAccess,
  GroupVaultAccess,
  Vault,
  VaultCreateParams,
  VaultGetParams,
  VaultListParams,
  VaultOverview,
  VaultUpdateParams,
  ReviverFunc,
} from "./types.js";

/**
 * The Vaults API holds all the operations the SDK client can perform on 1Password vaults.
 */
export interface VaultsApi {
  /**
   * Create a new user vault.
   */
  create(params: VaultCreateParams): Promise<Vault>;

  /**
   * List information about vaults that's configurable based on some input parameters.
   */
  list(params?: VaultListParams): Promise<VaultOverview[]>;

  /**
   * Get an overview of a vault by its ID.
   */
  getOverview(vaultId: string): Promise<VaultOverview>;

  /**
   * Get detailed vault information by vault ID and parameters.
   */
  get(vaultId: string, vaultParams: VaultGetParams): Promise<Vault>;

  /**
   * Update a vault
   */
  update(vaultId: string, params: VaultUpdateParams): Promise<Vault>;

  /**
   * Delete a vault by its ID.
   */
  delete(vaultId: string): Promise<void>;

  /**
   * Grant group permissions to a vault.
   */
  grantGroupPermissions(
    vaultId: string,
    groupPermissionsList: GroupAccess[],
  ): Promise<void>;

  /**
   * Update group permissions for vaults.
   */
  updateGroupPermissions(
    groupPermissionsList: GroupVaultAccess[],
  ): Promise<void>;

  /**
   * Revoke group permissions from a vault.
   */
  revokeGroupPermissions(vaultId: string, groupId: string): Promise<void>;
}

export class Vaults implements VaultsApi {
  #inner: InnerClient;

  public constructor(inner: InnerClient) {
    this.#inner = inner;
  }

  /**
   * Create a new user vault.
   */
  public async create(params: VaultCreateParams): Promise<Vault> {
    const invocationConfig: InvokeConfig = {
      invocation: {
        clientId: this.#inner.id,
        parameters: {
          name: "VaultsCreate",
          parameters: {
            params,
          },
        },
      },
    };
    return JSON.parse(
      await this.#inner.invoke(invocationConfig),
      ReviverFunc,
    ) as Vault;
  }

  /**
   * List information about vaults that's configurable based on some input parameters.
   */
  public async list(params?: VaultListParams): Promise<VaultOverview[]> {
    const invocationConfig: InvokeConfig = {
      invocation: {
        clientId: this.#inner.id,
        parameters: {
          name: "VaultsList",
          parameters: {
            params,
          },
        },
      },
    };
    return JSON.parse(
      await this.#inner.invoke(invocationConfig),
      ReviverFunc,
    ) as VaultOverview[];
  }

  /**
   * Get an overview of a vault by its ID.
   */
  public async getOverview(vaultId: string): Promise<VaultOverview> {
    const invocationConfig: InvokeConfig = {
      invocation: {
        clientId: this.#inner.id,
        parameters: {
          name: "VaultsGetOverview",
          parameters: {
            vault_id: vaultId,
          },
        },
      },
    };
    return JSON.parse(
      await this.#inner.invoke(invocationConfig),
      ReviverFunc,
    ) as VaultOverview;
  }

  /**
   * Get detailed vault information by vault ID and parameters.
   */
  public async get(
    vaultId: string,
    vaultParams: VaultGetParams,
  ): Promise<Vault> {
    const invocationConfig: InvokeConfig = {
      invocation: {
        clientId: this.#inner.id,
        parameters: {
          name: "VaultsGet",
          parameters: {
            vault_id: vaultId,
            vault_params: vaultParams,
          },
        },
      },
    };
    return JSON.parse(
      await this.#inner.invoke(invocationConfig),
      ReviverFunc,
    ) as Vault;
  }

  /**
   * Update a vault
   */
  public async update(
    vaultId: string,
    params: VaultUpdateParams,
  ): Promise<Vault> {
    const invocationConfig: InvokeConfig = {
      invocation: {
        clientId: this.#inner.id,
        parameters: {
          name: "VaultsUpdate",
          parameters: {
            vault_id: vaultId,
            params,
          },
        },
      },
    };
    return JSON.parse(
      await this.#inner.invoke(invocationConfig),
      ReviverFunc,
    ) as Vault;
  }

  /**
   * Delete a vault by its ID.
   */
  public async delete(vaultId: string): Promise<void> {
    const invocationConfig: InvokeConfig = {
      invocation: {
        clientId: this.#inner.id,
        parameters: {
          name: "VaultsDelete",
          parameters: {
            vault_id: vaultId,
          },
        },
      },
    };
    await this.#inner.invoke(invocationConfig);
  }

  /**
   * Grant group permissions to a vault.
   */
  public async grantGroupPermissions(
    vaultId: string,
    groupPermissionsList: GroupAccess[],
  ): Promise<void> {
    const invocationConfig: InvokeConfig = {
      invocation: {
        clientId: this.#inner.id,
        parameters: {
          name: "VaultsGrantGroupPermissions",
          parameters: {
            vault_id: vaultId,
            group_permissions_list: groupPermissionsList,
          },
        },
      },
    };
    await this.#inner.invoke(invocationConfig);
  }

  /**
   * Update group permissions for vaults.
   */
  public async updateGroupPermissions(
    groupPermissionsList: GroupVaultAccess[],
  ): Promise<void> {
    const invocationConfig: InvokeConfig = {
      invocation: {
        clientId: this.#inner.id,
        parameters: {
          name: "VaultsUpdateGroupPermissions",
          parameters: {
            group_permissions_list: groupPermissionsList,
          },
        },
      },
    };
    await this.#inner.invoke(invocationConfig);
  }

  /**
   * Revoke group permissions from a vault.
   */
  public async revokeGroupPermissions(
    vaultId: string,
    groupId: string,
  ): Promise<void> {
    const invocationConfig: InvokeConfig = {
      invocation: {
        clientId: this.#inner.id,
        parameters: {
          name: "VaultsRevokeGroupPermissions",
          parameters: {
            vault_id: vaultId,
            group_id: groupId,
          },
        },
      },
    };
    await this.#inner.invoke(invocationConfig);
  }
}
