name: Validate

on:
  push:
    paths-ignore:
      - '**.md'
jobs:

  test:
    name: Test
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        # actively maintained versions at the time of writing (Oct 4th, 2024)
        # https://nodejs.org/en/about/previous-releases
        node-version: ['18.x', '20.x', '22.x', 'latest']
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm install

      - name: Test
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
        run: npm test

      - name: Run esm-example
        if: matrix.os == 'ubuntu-latest' && matrix.node-version == '18.x'
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.EXAMPLE_TESTS_OP_SERVICE_ACCOUNT_TOKEN }}
          OP_VAULT_ID: ${{ secrets.EXAMPLE_TESTS_OP_VAULT_ID }}
        run: npm run esm-example

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm install

      - name: Style
        run: npm run prettier

      - name: Lint
        run: npm run eslint
